<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    //Index View
    '<strong>Share</strong> content' => '',
    'On your profile' => '',
    'On space' => '',
    'Share this content directly on your profile.' => '',
    'To share this content with other spaces, please type their names below to find and pick them.' => '',
    'You have already shared this post.' => '',
    'Please select at least one user' => '',

    //Success View
    'Shared!' => '',
    'Post has been shared successfully' => '',

    //Widgets
    '{displayName} shared a {contentType}.' => '',

    //Buttons
    'Share' => '',
    'Close' => '',
    'Ok' => '',
];
